(dp1
S'output'
p2
S'<class \'_mysql_exceptions.OperationalError\'> (1050, "Table \'oc_manufacturer\' already exists")'
p3
sS'layer'
p4
S'D:\\django\\web2py\\applications\\pb\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 0ABF84E8, file "D:\\django\\web2py\\applications\\pb\\models\\db.py", line 7>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "D:\\django\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "D:\\django\\web2py\\applications\\pb\\models\\db.py", line 150, in <module>\n    primarykey=[\'manufacturer_id\'],\n  File "D:\\django\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 586, in define_table\n    table = self.lazy_define_table(tablename, *fields, **args)\n  File "D:\\django\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 620, in lazy_define_table\n    polymodel=polymodel)\n  File "D:\\django\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 797, in create_table\n    return self.migrator.create_table(*args, **kwargs)\n  File "D:\\django\\web2py\\gluon\\packages\\dal\\pydal\\migrator.py", line 277, in create_table\n    self.adapter.create_sequence_and_triggers(query, table)\n  File "D:\\django\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 880, in create_sequence_and_triggers\n    self.execute(query)\n  File "D:\\django\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\__init__.py", line 67, in wrap\n    return f(*args, **kwargs)\n  File "D:\\django\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 412, in execute\n    rv = self.cursor.execute(command, *args[1:], **kwargs)\n  File "MySQLdb/cursors.py", line 205, in execute\n  File "MySQLdb/connections.py", line 36, in defaulterrorhandler\nOperationalError: (1050, "Table \'oc_manufacturer\' already exists")\n'
p11
s.